services:
    app:
        build:
            context: ./.docker/php
        container_name: symfony_app
        restart: unless-stopped
        tty: true
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
        working_dir: /var/www
        networks:
            - default

    nginx:
        image: nginx:stable-alpine
        container_name: symfony_nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx.default.conf:/etc/nginx/conf.d/default.conf
            - ./.docker/php/php.ini:/etc/php/8.4/fpm/conf.d/99-php.ini
            - ~/.ssh:/home/symfony/.ssh
        depends_on:
            - app
        networks:
            - default

    mysql:
        image: mysql:latest
        container_name: symfony_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_HOST: ${DB_HOST}:-'%'
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}:-'symfony'
            MYSQL_DATABASE: ${DB_DATABASE}:-'symfony'
            MYSQL_USER: ${DB_USER}:-'symfony'
            MYSQL_PASSWORD: ${DB_PASSWORD}:-'symfony'
            MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_ALLOW_EMPTY_PASSWORD}:-1
        volumes:
            - mysql-data:/var/lib/mysql
        ports:
            - ${MYSQL_PORT:-3306}:3306
        networks:
            - default

volumes:
    mysql-data:
        driver: local

networks:
    default:
        driver: bridge
